<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Kata_pro64_Cad2013</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="1dhhf4pVvUSHQVclA2Vt.jPqS5RpVrEnZJ0SgAOAd" />
    <None Remove="gE0dGPpVGduZrTW4ZbZ0.HF55rspVln9mQ8yWREC4" />
    <None Remove="aGJwEEpVQboc0Kl9cM0D.pi8h2IpV0W3eA4cGa08r" />
    <None Remove="p1p8ZqpVmlrslGtDcZKR.f4vUqxpVFY2efUIiHhI1" />
    <None Remove="hFyuIypVy9aC02ygA0Kk.C4hnIIpVzxwiws96XYLU" />
    <None Remove="QUQoEmpVMiAUQCK9hxHG.wRFJ39pVbiJ1eDg9vnQB" />
    <EmbeddedResource Include="1dhhf4pVvUSHQVclA2Vt.jPqS5RpVrEnZJ0SgAOAd" LogicalName="1dhhf4pVvUSHQVclA2Vt.jPqS5RpVrEnZJ0SgAOAd" />
    <EmbeddedResource Include="gE0dGPpVGduZrTW4ZbZ0.HF55rspVln9mQ8yWREC4" LogicalName="gE0dGPpVGduZrTW4ZbZ0.HF55rspVln9mQ8yWREC4" />
    <EmbeddedResource Include="aGJwEEpVQboc0Kl9cM0D.pi8h2IpV0W3eA4cGa08r" LogicalName="aGJwEEpVQboc0Kl9cM0D.pi8h2IpV0W3eA4cGa08r" />
    <EmbeddedResource Include="p1p8ZqpVmlrslGtDcZKR.f4vUqxpVFY2efUIiHhI1" LogicalName="p1p8ZqpVmlrslGtDcZKR.f4vUqxpVFY2efUIiHhI1" />
    <EmbeddedResource Include="hFyuIypVy9aC02ygA0Kk.C4hnIIpVzxwiws96XYLU" LogicalName="hFyuIypVy9aC02ygA0Kk.C4hnIIpVzxwiws96XYLU" />
    <EmbeddedResource Include="QUQoEmpVMiAUQCK9hxHG.wRFJ39pVbiJ1eDg9vnQB" LogicalName="QUQoEmpVMiAUQCK9hxHG.wRFJ39pVbiJ1eDg9vnQB" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="accoremgd" />
    <Reference Include="Kata_Class_Lib_Revit">
      <HintPath>C:\kata_pro\Kata_Class_Lib_Revit.dll</HintPath>
    </Reference>
    <Reference Include="Acdbmgd" />
    <Reference Include="System.Core" />
    <Reference Include="PresentationCore" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\kata_pro\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="iTextSharp.LGPLv2.Core">
      <HintPath>C:\kata_pro\iTextSharp.LGPLv2.Core.dll</HintPath>
    </Reference>
    <Reference Include="Docnet.Core">
      <HintPath>C:\kata_pro\Docnet.Core.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig">
      <HintPath>C:\kata_pro\UglyToad.PdfPig.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig.Core">
      <HintPath>C:\kata_pro\UglyToad.PdfPig.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\10.0.2\System.IO.Compression.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="Acmgd" />
    <Reference Include="QRCoder">
      <HintPath>C:\kata_pro\QRCoder.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="CSiAPIv1" />
    <Reference Include="System.Management" />
    <Reference Include="System.Security" />
    <Reference Include="WindowsBase" />
    <Reference Include="Security">
      <HintPath>C:\kata_pro\Security.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>